# Generated by Django 5.1 on 2024-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('title_inner', models.CharField(help_text='Inner title or organization name', max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
            ],
        ),
    ]
