# Generated by Django 5.1 on 2024-10-31 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
