# Generated by Django 5.1 on 2024-09-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
