# Generated by Django 5.1 on 2024-09-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_deliveryboy_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='date_of_birth',
        ),
    ]
