# Generated by Django 5.1 on 2024-10-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
                ('phonenumber', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
