# Generated by Django 5.1 on 2024-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
    ]
