# Generated by Django 5.1 on 2024-08-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_user_alter_cart_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
