# Generated by Django 5.1 on 2024-10-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_cart_unique_together_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
